BEGIN;

-- =========================================================
-- TENANTS TABLE
-- Stores the legal/business profile of a tenant.
-- A tenant record is separate from a login user account.
-- =========================================================

CREATE TABLE tenants (
    id BIGSERIAL PRIMARY KEY,

    public_id VARCHAR(50) NOT NULL,

    tenant_type VARCHAR(30) NOT NULL,

    display_name VARCHAR(200) NOT NULL,

    -- Individual tenant identifiers
    national_id VARCHAR(100),
    passport_number VARCHAR(100),

    -- Company, organization, partnership or government IDs
    registration_number VARCHAR(150),
    tax_identification_number VARCHAR(150),

    -- Contact information
    email VARCHAR(255),
    phone_number VARCHAR(50),
    alternative_phone VARCHAR(50),

    -- Physical/location information
    address TEXT,
    city VARCHAR(100),
    region VARCHAR(100),
    country VARCHAR(100) NOT NULL DEFAULT 'Tanzania',

    status VARCHAR(20) NOT NULL DEFAULT 'prospective',

    created_by BIGINT NOT NULL,

    created_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMPTZ NOT NULL
        DEFAULT CURRENT_TIMESTAMP,

    deleted_at TIMESTAMPTZ,

    CONSTRAINT uq_tenants_public_id
        UNIQUE (public_id),

    CONSTRAINT chk_tenants_type
        CHECK (
            tenant_type IN (
                'individual',
                'company',
                'government',
                'organization',
                'partnership'
            )
        ),

    CONSTRAINT chk_tenants_status
        CHECK (
            status IN (
                'prospective',
                'active',
                'inactive',
                'blocked'
            )
        ),

    CONSTRAINT chk_tenants_display_name
        CHECK (
            LENGTH(TRIM(display_name)) > 0
        ),

    CONSTRAINT fk_tenants_created_by
        FOREIGN KEY (created_by)
        REFERENCES users(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);


-- =========================================================
-- CURRENT TENANT IDENTIFIER UNIQUENESS
-- Soft-deleted tenants do not block future current records.
-- Identifiers are normalized using LOWER + TRIM.
-- =========================================================

CREATE UNIQUE INDEX
    uq_tenants_current_national_id
ON tenants (
    LOWER(TRIM(national_id))
)
WHERE deleted_at IS NULL
  AND national_id IS NOT NULL
  AND LENGTH(TRIM(national_id)) > 0;


CREATE UNIQUE INDEX
    uq_tenants_current_passport_number
ON tenants (
    LOWER(TRIM(passport_number))
)
WHERE deleted_at IS NULL
  AND passport_number IS NOT NULL
  AND LENGTH(TRIM(passport_number)) > 0;


CREATE UNIQUE INDEX
    uq_tenants_current_registration_number
ON tenants (
    LOWER(TRIM(registration_number))
)
WHERE deleted_at IS NULL
  AND registration_number IS NOT NULL
  AND LENGTH(TRIM(registration_number)) > 0;


CREATE UNIQUE INDEX
    uq_tenants_current_tax_identification_number
ON tenants (
    LOWER(TRIM(tax_identification_number))
)
WHERE deleted_at IS NULL
  AND tax_identification_number IS NOT NULL
  AND LENGTH(TRIM(tax_identification_number)) > 0;


-- =========================================================
-- QUERY PERFORMANCE INDEXES
-- =========================================================

CREATE INDEX idx_tenants_type
ON tenants (tenant_type)
WHERE deleted_at IS NULL;


CREATE INDEX idx_tenants_status
ON tenants (status)
WHERE deleted_at IS NULL;


CREATE INDEX idx_tenants_country
ON tenants (country)
WHERE deleted_at IS NULL;


CREATE INDEX idx_tenants_created_by
ON tenants (created_by);


CREATE INDEX idx_tenants_created_at
ON tenants (created_at DESC);


CREATE INDEX idx_tenants_display_name_search
ON tenants (
    LOWER(TRIM(display_name))
)
WHERE deleted_at IS NULL;


COMMENT ON TABLE tenants IS
'Stores tenant legal and business profiles separately from user login accounts.';


COMMENT ON COLUMN tenants.public_id IS
'Public API identifier generated by the application, for example tenant_xxxxx.';


COMMENT ON COLUMN tenants.tenant_type IS
'Supported values: individual, company, government, organization and partnership.';


COMMENT ON COLUMN tenants.status IS
'Lifecycle status: prospective, active, inactive or blocked.';


COMMENT ON COLUMN tenants.deleted_at IS
'Soft-delete timestamp. NULL means that the tenant is current.';

COMMIT;